### PR TITLE
Fix handling for WASI reactor modules

### LINKED ISSUE #35: Unexport `_initialize` from wizened WASI reactors
The `wizer.initialize` function is preserved in the snapshotted wasm module, but it's not expected to be called again, so it would be nice to add an option to strip the initialize function export, so that further optimization passes in other tools like `wasm-opt` can remove the unused initialization logic completely.

### PR DESCRIPTION
**Pull request by TerrorJack**
Closes #35.

### CODE REVIEW

**Review by fitzgen — COMMENTED** [review]
Thanks!

It looks like we are actually failing to call `_initialize` in the first place. Would you be up for adding that call, if `_initialize` is present, inside the `initialize` method at the bottom of `src/lib.rs` just before `self.init_func` is called? I think this also deserves a test in `tests/tests.rs`.

**Comment by TerrorJack** [comment]
Sure thing, I'll give it a try.

File: src/rewrite.rs [hunk 1]
```diff
@@ -129,12 +129,13 @@ impl Wizer {
...
-                // Remove the initialization function's export and perform any
-                // requested renames.
+                // Remove exports for the wizer initialization
+                // function and WASI reactor _initialize function,
+                // then perform any requested renames.
                 s if s.id == SectionId::Export.into() => {
                     let mut exports = wasm_encoder::ExportSection::new();
                     for export in module.exports(cx) {
-                        if export.field == self.init_func {
+                        if export.field == self.init_func || export.field == "_initialize" {
```
Comment (fitzgen) [inline src/rewrite.rs:138]: If there was a non-WASI reactor export named `_initialize` then this will remove it, even if we didn't already call its function (it might even be exporting a global or something like that). Since we check for the case where `_initialize` doesn't match the WASI reactor ABI and ignore it if it doesn't match during instantiation phase, that means we need to handle the ignored case later on, here, in the rewrite phase.

We can do this by passing a `bool` through to here that represents whether we called the WASI reactor `_initialize` function, and only remove the `_initialize` export if we called it already.

**Review by fitzgen — COMMENTED** [review]
Thanks!

One small thing to address before we merge this.

**Review by fitzgen — APPROVED** [review]
Thanks!
